### ISSUE TITLE
Incorrect assumption that chefspec is setup with no platforms

### ISSUE THREAD

**Issue by drrk** [chef-training/chef-intermediate#117]
The ChefDK installed on the latest version of the AMI is creating the chefspec with ServerRunner specifying Ubuntu 16.04  This means that both the refactoring is incorrect as we have been testing with a Ubuntu as the node type, and that the slide where we see the platform as 'chefspec' is also incorrect.

**Comment by burtlo** [comment]
You're very right. I'm fixing that now.

**Comment by burtlo** [comment]
All fixed and will be heading out in ver 3.0.0
