### ISSUE TITLE
Issues reported by Eric H

### ISSUE THREAD

**Issue by SteveDelFante** [chef-training/chef-intermediate#118]
The intermediate needs some tidying. It still has many screenshots showing the apache cookbook, not the httpd cookbook that we write in the class. Also several of the paths at the top of the page reflect this same issue. The pathing doesn't show that we are in the day_2 directory. We've just been telling students this. There is a slide that say that the rest of class is day_2, but really the path for each slide should ideally be corrected.

**Comment by burtlo** [comment]
I've now fixed this in the next release 3.0.0
