### ISSUE TITLE
Update: Introduction / Objectives Setup

### ISSUE THREAD

**Issue by burtlo** [chef-training/chef-intermediate#49]
### Purpose

This is an interim effort to correct any errors in the Chef Intermediate course. We will also do a full revision of this course in the near future.

### Note

Don’t worry about PPT formatting. Steve will integrate all content into the proper template and will manage formatting, spelling, grammar, etc.

### Work

1. Open up Modules/01-Chef_Intermediate.pptx
2. Update the content
3. Save the changes to the content
4. Commit the changes to the content
5. Push the finished version up
6. Notify @SteveDelFante in this issue

**Comment by nathenharvey** [comment]
@SteveDelFante see PR #62

**Comment by SteveDelFante** [comment]
@nathenharvey Nathan, I see you've updated modules 1 through 4 in your own branches and recommended deleting Module 5. (Thank you so much!). Is there any need for others to review those 4 modules or can I take your edits to the bank?
