### ISSUE TITLE
Update: Configuring Chef Clients

### ISSUE THREAD

**Issue by burtlo** [chef-training/chef-intermediate#51]
1. Open up Modules/03-Chef_Intermediate.pptx
2. Update the content
3. Save the changes to the content
4. Commit the changes to the content
5. Push the finished version up
6. Notify @SteveDelFante in this issue

**Comment by nathenharvey** [comment]
@SteveDelFante see pr #64

**Comment by nathenharvey** [comment]
I'm not sure this section is even required anymore.  

* The ssl warnings are gone with Chef 12
* The lab just makes the default behavior explicit
* There's not much new here relative to fundamentals
* This is blocker to getting to more interesting, relevant "intermediate" content.

**Comment by SteveDelFante** [comment]
@burtlo Franklin, would you agree that this module should be deleted?

**Comment by burtlo** [comment]
DELETE IT! :boom:

**Comment by burtlo** [comment]
Actually, I remembered that it the attendees do not finish this section the Ohai Section does not work!

The reason is that Ohai writes the path to load plugins and disable plugins through the `recipe[chef-client::config]` recipe. So this section is necessary and we are going to need to add this section back.
