### ISSUE TITLE
Update: chef-shell - The Chef Debugger

### ISSUE THREAD

**Issue by burtlo** [chef-training/chef-intermediate#53]
### Purpose

This is an interim effort to correct any errors in the Chef Intermediate course. We will also do a full revision of this course in the near future.

### Note

Don’t worry about PPT formatting. Steve will integrate all content into the proper template and will manage formatting, spelling, grammar, etc.

### Work

1. Open up Modules/05-Chef_Intermediate.pptx
2. Update the content
3. Save the changes to the content
4. Commit the changes to the content
5. Push the finished version up
6. Notify @SteveDelFante in this issue

**Comment by burtlo** [comment]
These are related issues. They don't have to be resolved for this section to be completed but at least reviewed.

- [ ] #13

**Comment by nathenharvey** [comment]
should we just abandon this section?

**Comment by SteveDelFante** [comment]
@burtlo Franklin, here's another module that could use your opinion about keeping it or not.

**Comment by burtlo** [comment]
The section has never been loved by anyone! :boom:
