### ISSUE TITLE
Update: Foodcritic

### ISSUE THREAD

**Issue by burtlo** [chef-training/chef-intermediate#58]
### Purpose

This is an interim effort to correct any errors in the Chef Intermediate course. We will also do a full revision of this course in the near future.

### Note

Don’t worry about PPT formatting. Steve will integrate all content into the proper template and will manage formatting, spelling, grammar, etc.

### Work

1. Open up Modules/10-Chef_Intermediate.pptx
2. Update the content
3. Save the changes to the content
4. Commit the changes to the content
5. Push the finished version up
6. Notify @SteveDelFante in this issue

**Comment by burtlo** [comment]
These are related issues. They don't have to be resolved for this section to be completed but at least reviewed.

- [ ] #25

**Comment by scarolan** [comment]
Walked through foodcritic module, verified against chef-fundamentals-repo.  I made a few small typo fixes, but overall this module was in good shape. @SteveDelFante, all yours

**Comment by SteveDelFante** [comment]
Awesome. Thanks so much Sean. If you feel like taking a look at one of the
other modules, please feel free. And thanks again!



*From:* Sean Carolan [mailto:notifications@github.com]
*Sent:* Friday, June 19, 2015 12:39 PM
*To:* chef-training/chef-intermediate
*Cc:* Steve Del Fante
*Subject:* Re: [chef-intermediate] Update: Foodcritic (#58)



Walked through foodcritic module, verified against chef-fundamentals-repo.
I made a few small typo fixes, but overall this module was in good shape.
@SteveDelFante <https://github.com/SteveDelFante>, all yours

—
Reply to this email directly or view it on GitHub
<https://github.com/chef-training/chef-intermediate/issues/58#issuecomment-113618188>
.

**Comment by SteveDelFante** [comment]
Updates complete pending Franklin's review in sd/hosted-chef-account branch.

**Comment by burtlo** [comment]
That's probably a poor branch to place it on as that one is for a different topic. I'll see what you added there and create a new one to merge.

**Comment by burtlo** [comment]
![screen shot 2015-06-22 at 3 19 05 pm](https://cloud.githubusercontent.com/assets/244426/8294563/1104de6a-18f2-11e5-8379-70280b3f92ce.png)

@SteveDelFante - @nathenharvey mentioned to you that this is in the ChefDK. I think that this should be updated to simply state this is in the ChefDK. Similar to Foodcritic section that I created in the https://github.com/chef-training/introduction_to_testing repo section on FoodCritic. This is also mentioned in the first 20 seconds of the video version https://www.youtube.com/watch?v=99fo8HKaBp4&list=PL11cZfNdwNyMp0BXY_nCOZ4odCqofq6oA&index=5.

Also, that section I wrote in the Introduction to Testing section I think should simply replace this section. I think that it gives a better introduction, example usage, and explanation of output.

**Comment by SteveDelFante** [comment]
Thanks for creating a better-named branch. I just used an existing one as you noticed...poorly named for this, I agree.

**Comment by burtlo** [comment]
I created the branch [near-term/foodcritic](https://github.com/chef-training/chef-intermediate/tree/) that I will open up a pull-request and merge.

**Comment by burtlo** [comment]
Also when I made those comments above I was looking at incorrect version of the deck. But the comments still stand -- they were made between @SteveDelFante and me through email. Taking them to GitHub to ensure we keep all the conversations and decisions centralized.

**Comment by SteveDelFante** [comment]
I'll be setting the version numbers for all of these modules to 1.2.0. The previous version was set as 1.1.4. I hope that's ok. When we do a major rev in the future I guess we will go to 2.0...I think we'll use a newer template by then too.

**Comment by burtlo** [comment]
@SteveDelFante that version numbering system makes sense. :+1:

**Comment by SteveDelFante** [comment]
Ultimately, I also want to include abbreviated module titles in the PPT file names. e.g., "03-Chef_Intermediate" might be re-named to something like 03-InterMed-ConfigChefClient.ppt. I am open to suggestions.

**Comment by burtlo** [comment]
Renaming those would be fine after we finish all this revising the content.

**Comment by burtlo** [comment]
I merged #61. So this is delivered.
