### ISSUE TITLE
Update: Rubocop

### ISSUE THREAD

**Issue by burtlo** [chef-training/chef-intermediate#59]
### Purpose

This is an interim effort to correct any errors in the Chef Intermediate course. We will also do a full revision of this course in the near future.

### Note

Don’t worry about PPT formatting. Steve will integrate all content into the proper template and will manage formatting, spelling, grammar, etc.

### Work

1. Open up Modules/11-Chef_Intermediate.pptx
2. Update the content
3. Save the changes to the content
4. Commit the changes to the content
5. Push the finished version up
6. Notify @SteveDelFante in this issue

**Comment by burtlo** [comment]
These are related issues. They don't have to be resolved for this section to be completed but at least reviewed.

- [ ] #25

**Comment by kennonkwok** [comment]
What is the starting point on this module?  Are we having folks install chefdk as a prerequisite to the course?

**Comment by SteveDelFante** [comment]
Yes. In module 01 the students are asked to install the latest chef-dk. If you are going to update/fix this module, please assign it to yourself if possible.

Thanks for your help!

**Comment by SteveDelFante** [comment]
Edited this deck after Kennon updated it. Edits complete and pushed to:
https://github.com/chef-training/chef-intermediate/tree/SD-Release-Candidates/Modules
